// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRbbeT-RyNZoRsIKcdA4T-CnH7Hhs82MY',
    appId: '1:671890368643:web:90af14f3da9db977a2d3b6',
    messagingSenderId: '671890368643',
    projectId: 'fruits-hub-e20b7',
    authDomain: 'fruits-hub-e20b7.firebaseapp.com',
    storageBucket: 'fruits-hub-e20b7.firebasestorage.app',
    measurementId: 'G-3LT3Z410WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIPXFfrF2I3CvXr9Wn7RBB9Q0LlokRQ7I',
    appId: '1:671890368643:android:a580808fb0199fc9a2d3b6',
    messagingSenderId: '671890368643',
    projectId: 'fruits-hub-e20b7',
    storageBucket: 'fruits-hub-e20b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4TimSmj67qjF1J_JMYZ4Ky1r8WJYM2UA',
    appId: '1:671890368643:ios:b4112b0d908a7a23a2d3b6',
    messagingSenderId: '671890368643',
    projectId: 'fruits-hub-e20b7',
    storageBucket: 'fruits-hub-e20b7.firebasestorage.app',
    androidClientId: '671890368643-snf0mtpbrh5oq9hd37qtd1eejp0po3sv.apps.googleusercontent.com',
    iosClientId: '671890368643-0n2oe9dnvdahdilcnesrumlf2t8bv0nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4TimSmj67qjF1J_JMYZ4Ky1r8WJYM2UA',
    appId: '1:671890368643:ios:b4112b0d908a7a23a2d3b6',
    messagingSenderId: '671890368643',
    projectId: 'fruits-hub-e20b7',
    storageBucket: 'fruits-hub-e20b7.firebasestorage.app',
    androidClientId: '671890368643-snf0mtpbrh5oq9hd37qtd1eejp0po3sv.apps.googleusercontent.com',
    iosClientId: '671890368643-0n2oe9dnvdahdilcnesrumlf2t8bv0nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRbbeT-RyNZoRsIKcdA4T-CnH7Hhs82MY',
    appId: '1:671890368643:web:2d0e1881628bc2a6a2d3b6',
    messagingSenderId: '671890368643',
    projectId: 'fruits-hub-e20b7',
    authDomain: 'fruits-hub-e20b7.firebaseapp.com',
    storageBucket: 'fruits-hub-e20b7.firebasestorage.app',
    measurementId: 'G-99TS48VX92',
  );
}
